spring.application.name=notification-service
server.port=8082
logging.pattern.console=%clr(%5p) %clr(${spring.application.name:-}){cyan} %clr(---){faint} %clr(%c{1}){magenta} : %m%n%wEx
spring.config.import=optional:file:.env[.properties]


spring.kafka.bootstrap-servers=localhost:29092
spring.kafka.consumer.group-id=notification-group
spring.kafka.consumer.properties.spring.json.trusted.packages=*


# SMTP server details
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${HOST_MAIL}
spring.mail.password=${MAIL_PASSWORD}

# Protocol and security
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.debug=true
spring.mail.default-encoding=UTF-8
