version: "3.9"
services:
  # Postgres for CustomerService
  postgres-customer:
    image: postgres:15
    container_name: customer_service_db
    environment:
      POSTGRES_USER: customer_service_user
      POSTGRES_PASSWORD: customer_service_pass
      POSTGRES_DB: customer_service_db
    volumes:
      - customer_service_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  # Customer Service
  customer-service:
    build: ./customer-service
    container_name: customer_service
    depends_on:
      - postgres-customer
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-customer:5432/customer_service_db
      SPRING_DATASOURCE_USERNAME: customer_service_user
      SPRING_DATASOURCE_PASSWORD: customer_service_pass
    ports:
      - "8089:8089"

volumes:
  customer_service_data: