version: "3.9"
services:
  # Postgres for CustomerService
  postgres-customer:
    image: postgres:15
    container_name: customer_service_db
    environment:
      POSTGRES_USER: customer_service_user
      POSTGRES_PASSWORD: customer_service_pass
      POSTGRES_DB: customer_service_db
    volumes:
      - customer_service_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  # Customer Service
  customer-service:
    build: ./customer-service
    container_name: customer_service
    depends_on:
      - postgres-customer
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-customer:5432/customer_service_db
      SPRING_DATASOURCE_USERNAME: customer_service_user
      SPRING_DATASOURCE_PASSWORD: customer_service_pass
    ports:
      - "8081:8081"

  # Postgres for NotificationService
  postgres-notification:
    image: postgres:15
    container_name: notification_service_db
    environment:
      POSTGRES_USER: notification_user
      POSTGRES_PASSWORD: notification_pass
      POSTGRES_DB: notification_db
    volumes:
      - notification_service_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  # Notification Service
  notification-service:
    build: ./notification-service
    container_name: notification_service
    depends_on:
      - postgres-notification
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-notification:5432/notification_db
      SPRING_DATASOURCE_USERNAME: notification_user
      SPRING_DATASOURCE_PASSWORD: notification_pass
    ports:
      - "8082:8082"

volumes:
  customer_service_data:
  notification_service_data:
