spring.application.name=customer-service
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/connector
spring.datasource.username=root
spring.datasource.password=ghulam
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:customer_data.sql
spring.sql.init.platform=postgresql