spring.application.name=customer-service
server.port=8081

spring.datasource.url=jdbc:postgresql://postgres-customer:5432/customer_service_db
spring.datasource.username=customer_service_user
spring.datasource.password=customer_service_pass

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:customer_data.sql
spring.sql.init.platform=postgresql

spring.kafka.bootstrap-servers=kafka-service:9093
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false